### ISSUE TITLE
Handle Panda does not exist

### ISSUE THREAD

**Issue by 55Dupup** [nickgkan/3d_diffuser_actor#78]
**The test times are wrong. What should I do?** 

Traceback (most recent call last):
  File "online_evaluation_rlbench/evaluate_policy.py", line 190, in <module>
    var_success_rates = env.evaluate_task_on_multiple_variations(
  File "/data/55d_1/3d_diffuser_actor/utils/utils_with_rlbench.py", line 425, in evaluate_task_on_multiple_variations
    self.env.launch()
  File "/data1/55d/3d_diffuser_actor/RLBench/rlbench/environment.py", line 103, in launch
    panda_arm = Panda()
  File "/home/dell/miniforge3/envs/3d_diffuser_actor/lib/python3.8/site-packages/pyrep/robots/arms/panda.py", line 12, in __init__
    super().__init__(
  File "/home/dell/miniforge3/envs/3d_diffuser_actor/lib/python3.8/site-packages/pyrep/robots/arms/arm.py", line 25, in __init__
    super().__init__(count, name, joint_names, base_name)
  File "/home/dell/miniforge3/envs/3d_diffuser_actor/lib/python3.8/site-packages/pyrep/robots/robot_component.py", line 19, in __init__
    super().__init__(
  File "/home/dell/miniforge3/envs/3d_diffuser_actor/lib/python3.8/site-packages/pyrep/objects/object.py", line 24, in __init__
    self._handle = sim.simGetObjectHandle(name_or_handle)
  File "/home/dell/miniforge3/envs/3d_diffuser_actor/lib/python3.8/site-packages/pyrep/backend/sim.py", line 94, in simGetObjectHandle
    raise RuntimeError('Handle %s does not exist.' % objectName)
RuntimeError: Handle Panda does not exist.

**Comment by nickgkan** [comment]
Hi,

This can happen if you don't install the correct CoppeliaSim version. Maybe try to uninstall and reinstall CoppeliaSIm/PyRep/RLBench following the instructions in the README?
